global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    # Scrapes container metrics
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    # Scrapes host machine metrics (CPU, RAM, Disk)
    static_configs:
      - targets: ['node-exporter:9100']